spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RededaLeitura?&serverTimezone=UTC
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

    
    